services:
  - type: web
    name: saaphzone-backend
    env: node
    plan: free
    region: ohio
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
